# Site Settings
baseurl: ""
url: "https://SuJeong2.github.io"

# Blog Settings
theme_settings:
  title: SuJeong2
  favicon: assets/writing.png

  # Profile Settings
  profile:
    image: assets/img/SuJeong2.jpg
    username: SUJEONG LEE
    description: <p>ìˆ˜ì •ì“°ì˜ ê¹ƒí—™ ë¸”ë¡œê·¸( â€¢Ì€ Ï‰ â€¢Ì )y </p> <p>ê³µë¶€í•˜ëŠ” ê²ƒë“¤ì„ ë„ì ì—¬ë³´ì!âœğŸ’» </p>
    experience:
      - start: 2021-01
        end: ing
        experience: ì‚¼ì„± ì²­ë…„ SW ì•„ì¹´ë°ë¯¸(SSAFY) 5ê¸°
      - start: 2021-02
        experience: ê°€ì²œëŒ€í•™êµ(Gachon University) ì¡¸ì—…
      - start: 2019-06
        end: 2019-11
        experience: 2019 SW ì±Œë¦°ì§€ ê³µëª¨ì „ <br>ë™ìƒ, í•œêµ­ SW ì‚°ì—…í˜‘íšŒì¥ìƒ ìˆ˜ìƒ
      - start: 2019-05
        experience: Ericsson-LG Girls in ICT 2019 í•´ì»¤í†¤ ì°¸ê°€ <br>ë³¸ì„  ì§„ì¶œ
      - start: 2018-07
        end: 2018-08
        experience: DPSOne ì‚°í•™ ì¸í„´
      - start: 2018-01
        end: 2018-12
        experience: í•™ë¶€ìƒ ì—°êµ¬ì› í™œë™
      - start: 2017-03
        end: 2017-06
        experience: ìŠ¤ë§ˆíŠ¸í° êµìœ¡ ë´‰ì‚¬
      - start: 2016-03
        experience: ê°€ì²œëŒ€í•™êµ(Gachon University) ì…í•™
    skills:
      - skill: Java
        value: 80 # Percent value
      - skill: Spring
        value: 70 # Percent value

  # Icons
  icons:
    email: "lee.sujeong10111@gmail.com"
    linkedin: # Full URL
    github: SuJeong2
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: sue_jjng
    blog: sj971020
    portfolio: portfolio

  # Disqus
  disqus_shortname:

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
