# Site Settings
baseurl: ""
url: "https://SuJeong2.github.io"

# Blog Settings
theme_settings:
  title: SuJeong2
  favicon: assets/writing(1).png

  # Profile Settings
  profile:
    image: assets/img/SuJeong2.jpg
    username: SUJEONG LEE
    description: <p>ìˆ˜ì •ì“°ì˜ ê¹ƒí—™ ë¸”ë¡œê·¸( â€¢Ì€ Ï‰ â€¢Ì )y </p> <p>ê³µë¶€í•˜ëŠ” ê²ƒë“¤ì„ ë„ì ì—¬ë³´ì!âœğŸ’» </p>
    experience:
      - start: 2021-01
        end: ing
        experience: ì‚¼ì„± ì²­ë…„ SW ì•„ì¹´ë°ë¯¸(SSAFY) 5ê¸°
      - start: 2016-03
        end: 2021-02
        experience: ê°€ì²œëŒ€í•™êµ(Gachon University) ì¡¸ì—…
    skills:
      - skill: Java
        value: 80 # Percent value
      - skill: Spring
        value: 70 # Percent value

  # Icons
  icons:
    email: "lee.sujeong10111@gmail.com"
    linkedin: # Full URL
    github: SuJeong2
    gitlab:
    bitbucket:
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram: sue_jjng
    blog: sj971020
    portfolio: portfolio

  # Disqus
  disqus_shortname:

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
